0.algumasCoisas/sirus/djangoAulaSite/django1/main/urls.py
from django.contrib import admin
from django.urls import path
from core.views import index

from django.conf import settings
from django.conf.urls.static import static
from core.views import index, produto, produto_submit, login_user, login_submit

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('produto/', produto, name='produto'),
    path('produto/submit', produto_submit, name='produto_submit'),
    path('login/', login_user, name='login'),
    path('login/submit', login_submit, name='login_submit'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



0.algumasCoisas/sirus/djangoAulaSite/django1/core/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User



# Create your models here.


class Produto(models.Model):
    nome = models.CharField('Nome', max_length=100)
    preco = models.DecimalField('Preco', decimal_places=2, max_digits=15)
    estoque = models.IntegerField('qtd no estoque')
    imagem = models.ImageField('IMG', blank=True, upload_to='core')
    usuario = models.ForeignKey(
        User, null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='usuario_produto',
        
        )

    
    def __str__(self) -> str:
        return self.nome
        
class Cliente(models.Model):
    nome = models.CharField('nome', max_length=100)
    sobrenome = models.CharField('sobrenome', max_length=100)
    email = models.EmailField('email', max_length=150, unique=True)
    data_nascimento = models.DateField('data nascimento', blank=True, null=True)


0.algumasCoisas/sirus/djangoAulaSite/django1/core/forms.py
from socket import fromshare
from django import forms

from .models import Produto

class ProdutoModelForm(forms.ModelForm):
    class Meta:
        model = Produto
        # para pegar todos
        # fields = '__all__' 
        
        # outro jeito com dicionario
        fields = ['nome', 'preco', 'estoque', 'imagem']

0.algumasCoisas/sirus/djangoAulaSite/django1/core/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate


from .models import Produto
from .forms import ProdutoModelForm
# Create your views here.

def login_user(request):
    # se ja estiver logado, nao fazer login de novo
    if request.user.is_authenticated:
        return redirect('/')
    
    return render(request, 'login.html')

def login_submit(request):
    if request.method == 'POST':
        if request.POST:
            usuario = request.POST.get('usuario')
            senha = request.POST.get('senha')
            user = authenticate(username=usuario, password=senha)

            if user:
                messages.success(request, 'login feito com sucesso')
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'error: usuario ou senha invalidos')
                return render(request, 'login.html')
                
    messages.error(request, 'erro ao logar, nao envio de dados')

    return render(request, 'login.html')


    
def index(request):
    print('=-'*49)
    print(dir(request.user))
    print(request.user.username)
    print('=-'*49)
    
    produtos = Produto.objects.all().order_by('-id')

    context = {
        'meu_titulo': 'lista de produtos',
        'produtos': produtos
    }
    return render(request, 'index.html', context)

def produto(request):
    if request.method == 'POST':
        form = ProdutoModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto salvo com sucesso')
            form = ProdutoModelForm()
        else:
            messages.error(request, 'erro ao salvar o produto')    
    else:
        form = ProdutoModelForm()
    context = {'form': form}

    return render(request, 'produto.html', context)


def produto_submit(request):
    if request.method == 'POST':
        form = ProdutoModelForm(request.POST, request.FILES)
        if form.is_invalid():
            form.save()
            return redirect('index')
        else:
            messages.error(request, 'erro ao salvar o produto')
            return render(request, 'produto.html')
    else:
        return redirect('index')

0.algumasCoisas/sirus/djangoAulaSite/django1/core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>so um teste</h1>
    {% if request.user.is_anonymous %}
        <h2><a href=""> faca login </a></h2>
    {% else %}
        <h2> bem vindo {{ request.user.username }}</h2>
    {% endif %}
    <hr>
    
    <h1>{{ meu_titulo }}</h1>
    <ul>
        {% for item in produtos %}
            {% if item.imagem %}
                <img src='/media/{{ item.imagem }} '\>
            {% endif %}

            <li> {{ item.id }} - {{ item.nome }} - {{ item.preco }}</li>
        {% endfor %}
    </ul>

</body>
</html>

0.algumasCoisas/sirus/djangoAulaSite/django1/core/templates/login.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
    {% bootstrap_css %}

</head>
<body bgcolor="lightgreen">
    <div class="container">
        <h1>login</h1>
        <hr>
        {% bootstrap_messages %}
        <form action="/login/submit" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="usuario"> usuario:</label><br>
            <input type="text" name="usuario" value=""><br>
            <label for="senha"> senha:</label><br>
            <input type="password" name="senha" value=""><br>
            <input type="submit" class="btn btn-primary" value="Submit">


            

        </form>
    </div>
{% bootstrap_javascript %}
</body>
</html>

0.algumasCoisas/sirus/djangoAulaSite/django1/core/templates/produto.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cadastro de produto</title>
    {% bootstrap_css %}

</head>
<body bgcolor="lightgreen">
    <div class="container">
        <h1>Produto</h1>
        {% bootstrap_messages %}
        <form action="{% url 'produto' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            {% endbuttons %}
            

        </form>
    </div>
{% bootstrap_javascript %}
</body>
</html>

0.algumasCoisas/sirus/djangoAulaSite/django1/core/templates/produto2.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cadastro de produto</title>
</head>
<body bgcolor="lightgreen">
    <h1 fg="red">produto</h1>
    <hr>

    <form action="submit">
        {% csrf_token %}
        <label for="nome">nome do produto:</label>
        <input type="text" id="nome" name="nome" value=""><br>
        <label for="preco">preco:</label>
        <input type="text" id="preco" name="preco" value=""><br><br>
        <label for="estoque" >estoque:</label>
        <input type="number" id="estoque" name="estoque" value=""><br><br>
        <input type="file" id="id_imagem" name="imagem" accept="image/*"><br>
        <input type="submit" value="Submit">
    </form>
    <hr>
</body>
</html>